# Generated by Django 2.1.2 on 2018-10-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='comment',
        ),
    ]
