# Generated by Django 2.1.2 on 2018-10-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0013_auto_20181011_1025'),
        ('Announcement', '0002_remove_announcement_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement', to='Comment.Comment'),
        ),
    ]
