# Generated by Django 2.1.2 on 2018-10-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0003_auto_20181010_1127'),
        ('Announcement', '0003_announcement_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_announcement', to='Classroom.Classroom'),
            preserve_default=False,
        ),
    ]
