# Generated by Django 2.1.2 on 2018-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
