# Generated by Django 2.1.2 on 2018-10-10 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='moderators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
