# Generated by Django 2.1.2 on 2018-10-10 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classroom', '0002_classroom_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='all_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='moderators',
            field=models.ManyToManyField(related_name='all_moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
