# Generated by Django 2.1.2 on 2018-10-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_auto_20181010_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
    ]
