# Generated by Django 2.1.2 on 2018-10-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0005_comment_commenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
