# Generated by Django 2.1.2 on 2018-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0007_auto_20181010_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
