# Generated by Django 2.1.2 on 2018-10-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0008_comment_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
    ]
